"use strict";

export function languageCodeToName(code) {
  const map = {
    Base: "English",
    English: "English",
    en: "English (United States)",
    en_AU: "English (Australia)",
    en_CA: "English (Canada)",
    en_GB: "English (United Kingdom)",
    en_ID: "English (Indonesia)",
    en_IN: "English (India)",
    en_MY: "English (Malaysia)",
    en_NZ: "English (New Zealand)",
    en_SG: "English (Singapore)",
    French: "French",
    fr: "French (France)",
    fr_BE: "French (Belgium)",
    fr_CA: "French (Canada)",
    fr_CH: "French (Switzerland)",
    German: "German",
    de: "German (Germany)",
    "de-AT": "German (Austria)",
    "de-CH": "German (Switzerland)",
    Italian: "Italian",
    it: "Italian (Italy)",
    it_CH: "Italian (Switzerland)",
    Japanese: "Japanese",
    ja: "Japanese (Japan)",
    Spanish: "Spanish",
    es: "Spanish (Spain)",
    es_419: "Spanish (Latin America)",
    es_AR: "Spanish (Argentina)",
    es_CL: "Spanish (Chile)",
    es_CR: "Spanish (Costa Rica)",
    es_CO: "Spanish (Colombia)",
    es_GT: "Spanish (Guatemala)",
    es_MX: "Spanish (Mexico)",
    es_PA: "Spanish (Panama)",
    es_PE: "Spanish (Peru)",
    sq: "Albanian (Albania)",
    ar: "Arabic (Saudi Arabia)",
    ar_AE: "Arabic (United Arab Emirates)",
    ar_SA: "Arabic (Saudi Arabia)",
    hy: "Armenian (Armenia)",
    az: "Azerbaijani (Azerbaijan)",
    bn: "Bengali (Bangladesh)",
    bg: "Bulgarian (Bulgaria)",
    my: "Burmese (Myanmar)",
    ca: "Catalan (Spain)",
    km: "Central Khmer (Cambodia)",
    hr: "Croatian (Croatia)",
    cs: "Czech (Czech Republic)",
    da: "Danish (Denmark)",
    Dutch: "Dutch (Netherlands)",
    nl: "Dutch (Netherlands)",
    ka: "Georgian (Georgia)",
    el: "Greek (Greece)",
    et: "Estonian (Estonia)",
    fi: "Finnish (Finland)",
    gu_Latn: "Gujarati (India)",
    he: "Hebrew",
    hi: "Hindi (India)",
    hi_Latn: "Hindi (India)",
    hu: "Hungarian (Hungary)",
    is: "Icelandic (Iceland)",
    id: "Indonesian (Indonesia)",
    kn_Latn: "Kannada (India)",
    kk: "Kazakh (Kazakhstan)",
    ko: "Korean (South Korea)",
    lo: "Lao (Laos)",
    lv: "Latvian (Latvia)",
    ml_Latn: "Malayalam (India)",
    mr: "Marathi (India)",
    mr_Latn: "Marathi (India)",
    ms: "Malay (Malaysia)",
    no: "Norwegian (Norway)",
    nb: "Norwegian Bokmål (Norway)",
    or_Latn: "Oriya (India)",
    pa: "Punjabi (India)",
    pa_Latn: "Punjabi (India)",
    pl: "Polish (Poland)",
    pt: "Portuguese (Brazil)",
    pt_BR: "Portuguese (Brazil)",
    pt_PT: "Portuguese (Portugal)",
    ro: "Romanian (Romania)",
    ru: "Russian (Russia)",
    sk: "Slovak (Slovakia)",
    sv: "Swedish (Sweden)",
    ta: "Tamil (India)",
    ta_Latn: "Tamil (India)",
    te_Latn: "Telugu (India)",
    th: "Thai (Thailand)",
    tr: "Turkish (Turkey)",
    uk: "Ukrainian (Ukraine)",
    ur: "Urdu (Pakistan)",
    uz: "Uzbek (Uzbekistan)",
    vi: "Vietnamese (Vietnam)",
    "zh-Hans": "Chinese (China)",
    zh_CN: "Chinese (China)",
    "zh-Hant": "Chinese",
    zh_HK: "Chinese (Hong Kong)",
    zh_TW: "Chinese (Taiwan)",
    yue: "Cantonese (Hong Kong)",
    "yue-CN": "Cantonese (Hong Kong)",
  };

  const c = code
    .replace("-iphoneos", "")
    .replace("-macos", "")
    .replace("-tvos", "")
    .replace("~applewatch", "")
    .replace("~ipad", "")
    .replace("~iphone", "");

  return map[c] || code;
}
