services:
  db:
    image: kishikawakatsumi/applelocalization-data:latest
    container_name: applelocalization-data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    image: kishikawakatsumi/applelocalization-web:latest
    container_name: applelocalization-web
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 10000
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 80:8080
    depends_on:
      - db
