version: "3.9"
services:
  db:
    image: kishikawakatsumi/applelocalization-data:latest
    container_name: applelocalization-data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:10000
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FONTAWESOME_TOKEN=${FONTAWESOME_TOKEN}
    container_name: applelocalization-web
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 10000
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 8080:8080
    depends_on:
      - db
