export const languageMapping: { [key: string]: string[] } = {
  English: [
    "Base",
    "English",
    "en",
    "en-GB",
    "en-iphoneos",
    "en-macos",
    "en-tvos",
    "en_AU",
    "en_AU-iphoneos",
    "en_AU-macos",
    "en_AU-tvos",
    "en_AU~applewatch",
    "en_AU~ipad",
    "en_AU~iphone",
    "en_CA",
    "en_GB",
    "en_GB-iphoneos",
    "en_GB-macos",
    "en_GB-tvos",
    "en_GB~applewatch",
    "en_GB~ipad",
    "en_GB~iphone",
    "en_IN",
    "en~applewatch",
    "en~ipad",
    "en~iphone",
  ],
  French: [
    "French",
    "fr",
    "fr-CA",
    "fr-iphoneos",
    "fr-macos",
    "fr-tvos",
    "fr_CA",
    "fr_CA-iphoneos",
    "fr_CA-macos",
    "fr_CA-tvos",
    "fr_CA~applewatch",
    "fr_CA~ipad",
    "fr_CA~iphone",
    "fr~applewatch",
    "fr~ipad",
    "fr~iphone",
  ],
  German: [
    "German",
    "de",
    "de-iphoneos",
    "de-macos",
    "de-tvos",
    "de~applewatch",
    "de~ipad",
    "de~iphone",
  ],
  Italian: [
    "Italian",
    "it",
    "it-iphoneos",
    "it-macos",
    "it-tvos",
    "it~applewatch",
    "it~ipad",
    "it~iphone",
  ],
  Japanese: [
    "Japanese",
    "ja",
    "ja-iphoneos",
    "ja-macos",
    "ja-tvos",
    "ja~applewatch",
    "ja~ipad",
    "ja~iphone",
  ],
  Spanish: [
    "Spanish",
    "es",
    "es-iphoneos",
    "es-macos",
    "es-tvos",
    "es_419",
    "es_419-iphoneos",
    "es_419-macos",
    "es_419-tvos",
    "es_419~applewatch",
    "es_419~ipad",
    "es_419~iphone",
    "es_MX",
    "es~applewatch",
    "es~ipad",
    "es~iphone",
  ],
  Albanian: [
    "sq",
  ],
  Arabic: [
    "ar",
    "ar-iphoneos",
    "ar-macos",
    "ar-tvos",
    "ar~applewatch",
    "ar~ipad",
    "ar~iphone",
  ],
  Armenian: [
    "hy",
  ],
  Azerbaijani: [
    "az",
  ],
  Bengali: [
    "bn",
  ],
  Bulgarian: [
    "bg",
    "bg-iphoneos",
    "bg-macos",
    "bg-tvos",
    "bg~applewatch",
    "bg~iphone",
  ],
  Burmese: [
    "my",
  ],
  Catalan: [
    "ca",
    "ca-iphoneos",
    "ca-macos",
    "ca-tvos",
    "ca~applewatch",
    "ca~ipad",
    "ca~iphone",
  ],
  "Central Khmer": [
    "km",
  ],
  Croatian: [
    "hr",
    "hr-iphoneos",
    "hr-macos",
    "hr-tvos",
    "hr~applewatch",
    "hr~ipad",
    "hr~iphone",
  ],
  Czech: [
    "cs",
    "cs-iphoneos",
    "cs-macos",
    "cs-tvos",
    "cs~applewatch",
    "cs~ipad",
    "cs~iphone",
  ],
  Danish: [
    "da",
    "da-iphoneos",
    "da-macos",
    "da-tvos",
    "da~applewatch",
    "da~ipad",
    "da~iphone",
  ],
  Dutch: [
    "Dutch",
    "nl",
    "nl-iphoneos",
    "nl-macos",
    "nl-tvos",
    "nl~applewatch",
    "nl~ipad",
    "nl~iphone",
  ],
  Georgian: [
    "ka",
  ],
  Greek: [
    "el",
    "el-iphoneos",
    "el-macos",
    "el-tvos",
    "el~applewatch",
    "el~ipad",
    "el~iphone",
  ],
  Estonian: [
    "et",
  ],
  Filipino: [
    "fil",
  ],
  Finnish: [
    "fi",
    "fi-iphoneos",
    "fi-macos",
    "fi-tvos",
    "fi~applewatch",
    "fi~ipad",
    "fi~iphone",
  ],
  Gujarati: [
    "gu_Latn",
  ],
  Hebrew: [
    "he",
    "he-iphoneos",
    "he-macos",
    "he-tvos",
    "he~applewatch",
    "he~ipad",
    "he~iphone",
  ],
  Hindi: [
    "hi",
    "hi-iphoneos",
    "hi-macos",
    "hi-tvos",
    "hi_Latn",
    "hi~applewatch",
    "hi~ipad",
    "hi~iphone",
  ],
  Hungarian: [
    "hu",
    "hu-iphoneos",
    "hu-macos",
    "hu-tvos",
    "hu~applewatch",
    "hu~ipad",
    "hu~iphone",
  ],
  Icelandic: [
    "is",
  ],
  Indonesian: [
    "id",
    "id-iphoneos",
    "id-macos",
    "id-tvos",
    "id~applewatch",
    "id~ipad",
    "id~iphone",
  ],
  Kannada: [
    "kn_Latn",
  ],
  Kazakh: [
    "kk",
    "kk-iphoneos",
    "kk-macos",
    "kk-tvos",
    "kk~applewatch",
    "kk~iphone",
  ],
  Korean: [
    "ko",
    "ko-iphoneos",
    "ko-macos",
    "ko-tvos",
    "ko~applewatch",
    "ko~ipad",
    "ko~iphone",
  ],
  Lao: [
    "lo",
  ],
  Latvian: [
    "lv",
  ],
  Lithuanian: [
    "lt",
  ],
  Malayalam: [
    "ml_Latn",
  ],
  Marathi: [
    "mr",
  ],
  Malay: [
    "ms",
    "ms-iphoneos",
    "ms-macos",
    "ms-tvos",
    "ms~applewatch",
    "ms~ipad",
    "ms~iphone",
  ],
  Mongolian: [
    "mn",
  ],
  Norwegian: [
    "no",
    "no-iphoneos",
    "no-macos",
    "no-tvos",
    "no~applewatch",
    "no~ipad",
    "no~iphone",
  ],
  "Norwegian Bokmål": [
    "nb",
  ],
  Oriya: [
    "or_Latn",
  ],
  Punjabi: [
    "pa",
  ],
  Polish: [
    "pl",
    "pl-iphoneos",
    "pl-macos",
    "pl-tvos",
    "pl~applewatch",
    "pl~ipad",
    "pl~iphone",
  ],
  Portuguese: [
    "pt",
    "pt-PT",
    "pt-iphoneos",
    "pt-macos",
    "pt_BR",
    "pt_BR-iphoneos",
    "pt_BR-macos",
    "pt_BR-tvos",
    "pt_BR~ipad",
    "pt_BR~iphone",
    "pt_PT",
    "pt_PT-iphoneos",
    "pt_PT-macos",
    "pt_PT-tvos",
    "pt_PT~applewatch",
    "pt_PT~ipad",
    "pt_PT~iphone",
    "pt~applewatch",
    "pt~ipad",
    "pt~iphone",
  ],
  Romanian: [
    "ro",
    "ro-iphoneos",
    "ro-macos",
    "ro-tvos",
    "ro~applewatch",
    "ro~ipad",
    "ro~iphone",
  ],
  Russian: [
    "ru",
    "ru-iphoneos",
    "ru-macos",
    "ru-tvos",
    "ru~applewatch",
    "ru~ipad",
    "ru~iphone",
  ],
  Slovak: [
    "sk",
    "sk-iphoneos",
    "sk-macos",
    "sk-tvos",
    "sk~applewatch",
    "sk~ipad",
    "sk~iphone",
  ],
  Swedish: [
    "sv",
    "sv-iphoneos",
    "sv-macos",
    "sv-tvos",
    "sv~applewatch",
    "sv~ipad",
    "sv~iphone",
  ],
  Tamil: [
    "ta",
  ],
  Thai: [
    "th",
    "th-iphoneos",
    "th-macos",
    "th-tvos",
    "th~applewatch",
    "th~ipad",
    "th~iphone",
  ],
  Turkish: [
    "tr",
    "tr-iphoneos",
    "tr-macos",
    "tr-tvos",
    "tr~applewatch",
    "tr~ipad",
    "tr~iphone",
  ],
  Ukrainian: [
    "uk",
    "uk-iphoneos",
    "uk-macos",
    "uk-tvos",
    "uk~applewatch",
    "uk~ipad",
    "uk~iphone",
  ],
  Urdu: [
    "ur",
  ],
  Uzbek: [
    "uz",
  ],
  Vietnamese: [
    "vi",
    "vi-iphoneos",
    "vi-macos",
    "vi-tvos",
    "vi~applewatch",
    "vi~ipad",
    "vi~iphone",
  ],
  "Simplified Chinese": [
    "zh-Hans",
    "zh_CN",
    "zh_CN-iphoneos",
    "zh_CN-macos",
    "zh_CN-tvos",
    "zh_CN~applewatch",
    "zh_CN~ipad",
    "zh_CN~iphone",
  ],
  "Traditional Chinese": [
    "zh-Hant",
    "zh_HK",
    "zh_HK-iphoneos",
    "zh_HK-macos",
    "zh_HK-tvos",
    "zh_HK~applewatch",
    "zh_HK~ipad",
    "zh_HK~iphone",
    "zh_TW",
    "zh_TW-iphoneos",
    "zh_TW-macos",
    "zh_TW-tvos",
    "zh_TW~applewatch",
    "zh_TW~ipad",
    "zh_TW~iphone",
  ],
  Cantonese: [
    "yue-CN",
  ],
};
