name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          build-args: FONTAWESOME_TOKEN=${{ secrets.FONTAWESOME_TOKEN }}
          push: true
          tags: kishikawakatsumi/applelocalization-web:latest

      - uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd applelocalization-web

            docker compose down
            docker system prune --all -f
            docker system prune --volumes -f
            docker compose up -d
